version: '3.9'

services:
  advertisement-system:
    build:
      dockerfile: Dockerfile
      context: ./
    image: cyjay96/advertisement-system
    ports:
      - "8080:8080"
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: advertisement_system
    networks:
      - postgres-network
    restart: unless-stopped

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: advertisement_system
    networks:
      - postgres-network
    restart: unless-stopped

networks:
  postgres-network:
